### PR TITLE
Add British Columbia as a region

### PR DESCRIPTION
**Pull request by pnorman**
This is ready to go except that copyright information needs adding. The geojson is derived from OSM data.

### CODE REVIEW

**Comment by jbelien** [comment]
Hello @pnorman ! Thanks a lot for your contribution !

I've finalized the PR.

Concerning the copyright information, the correct attribution is displayed on the map where the GeoJSON is also displayed (see below).
Do you want me to add the attribution else where ? And if so, where would you want to see it ?

image

**Comment by pnorman** [comment]
> Do you want me to add the attribution else where ? And if so, where would you want to see it ?

It needs to be in the repo somewhere - maybe a file in assets/regions? The instructions say to make something derived from OSM data, so it would make sense to just license all the files there under the ODbL

**Comment by jbelien** [comment]
> It needs to be in the repo somewhere - maybe a file in assets/regions?

Good idea! I'll add a README file in `assets/regions` folder.
And add some attribution (OSM + OSMCha) in the main README. 👌

**Comment by jbelien** [comment]
I've added a README (and a LICENSE file) in the `assets/regions` folder: https://github.com/osmbe/osm-welcome-tool/tree/2.x/assets/regions

**Comment by jbelien** [comment]
Deployed: https://welcome.osm.be/ca-bc/list 🚀

**Pull request merged**
