### PR TITLE
Add Massachusetts, USA

### PR DESCRIPTION
**Pull request by JesseWeinstein**
Adding Massachusetts. Thanks for the useful tool (and clear instructions for adding regions)!

### CODE REVIEW

**Comment by jbelien** [comment]
Awesome ! 🎉 

Here you go: https://welcome.osm.be/massachusetts/list 🚀

**Comment by JesseWeinstein** [comment]
Whoops, looks like the server is down right now?

**Comment by jbelien** [comment]
> Whoops, looks like the server is down right now?

Damn, don't know what happened. I'll check tonight.

**Comment by jbelien** [comment]
@JesseWeinstein It should be back!

**Pull request merged**
