### PR TITLE
Update regions.yaml

### PR DESCRIPTION
**Pull request by GITMichaelK**
added: germany

### CODE REVIEW

**Comment by jbelien** [comment]
Hello @GITMichaelK,

Thank you for your contribution.
Could you follow the [contributing guidelines](https://github.com/osmbe/osm-welcome-tool/blob/2.x/CONTRIBUTING.md#add-a-new-region) and add what's missing (GeoJSON file of the region)?

**Comment by GITMichaelK** [comment]
Hello @jbelien,
Thank you and sorry that I missed the GeoJSON file, I did my best to add it now; however I'm not sure if it's correct: I used http://polygons.openstreetmap.fr/?id=51477
How to get the checks from a maintainer?
Thanks!!

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/germany/list

**Comment by jbelien** [comment]
There seems to be an issue in the process for Germany currently, I'll have a look.

**Comment by jbelien** [comment]
Follow up on the issue will be tackled in #262

**Pull request merged**
