### PR TITLE
Update regions.yaml

### PR DESCRIPTION
**Pull request by jqngarcia**
Upate Països Catalans

### CODE REVIEW

**Comment by jbelien** [comment]
Hello @jqngarcia,

Thank you for your contribution.
Could you follow the [contributing guidelines](https://github.com/osmbe/osm-welcome-tool/blob/2.x/CONTRIBUTING.md#add-a-new-region) and add what's missing (GeoJSON file of the region)?

**Comment by jqngarcia** [comment]
Upload files are disabled, I can't upload Geojson

**Comment by jbelien** [comment]
> Upload files are disabled, I can't upload Geojson

You need to upload it in your own repository (fork of this one): https://github.com/jqngarcia/osm-welcome-tool/tree/patch-1/assets/regions

**Comment by jqngarcia** [comment]
Thanks doit

**Review by jbelien — CHANGES_REQUESTED** [review]
Your `catalan_countries.geojson` file is not a valid GeoJSON file.
It seems to be a HTML file.

What's the OpenStreetMap relation id of the region you want to add to the Welcome Tool ?

**Comment by jqngarcia** [comment]
I upload a new json,

this is the polygon https://www.openstreetmap.org/relation/11747082

**Review by jbelien — CHANGES_REQUESTED** [review]
I've fixed the GeoJSON file.

The `flag` parameter in `regions.yaml` file must be an Emoji.
Is there an Emoji for Catalan Countries ? If not, what Emoji do you want ?

**Comment by jqngarcia** [comment]
Please Jonathan put a emoji to cat is the arcronim of Catalonia, thanks

**Comment by jbelien** [comment]
> Please Jonathan put a emoji to cat is the arcronim of Catalonia, thanks

A cat emoji ? Like this one 🐱 ? Or this one 🐈 ?
You can find (and copy) the emoji you want from https://emojipedia.org/search/?q=cat (for instance).

**Comment by jqngarcia** [comment]
Can put thi image?

https://user-images.githubusercontent.com/35226532/144995521-308293ba-c15f-4fd6-b6a7-a0baa0681d03.png

**Comment by jbelien** [comment]
> Can put thi image?
> 
> https://user-images.githubusercontent.com/35226532/144995521-308293ba-c15f-4fd6-b6a7-a0baa0681d03.png

No sorry, the Welcome Tool only supports Emoji for now (no image).

**Comment by jqngarcia** [comment]
Ok put cat face emoji.

Thanks for all

**Comment by jbelien** [comment]
I've done some research and there is an emoji for Catalonia (ES-CT) : https://emojipedia.org/flag-for-catalonia-esct/ 🏴󠁥󠁳󠁣󠁴󠁿

Not supported a lot (yet?) so it will be displayed as a black flag for now (like Scotland).
image

But will be replace by the correct flag as soon as it is supported.

Would you prefer that option instead of the cat 🐱 ?

**Comment by jqngarcia** [comment]
ok put black flag

**Review by jbelien — APPROVED** [review]

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/catalan_countries/list

**Pull request merged**
