### PR TITLE
Fix France region

### PR DESCRIPTION
**Pull request by llongour**
Hello,
Currently the France page is not working, this PR modifies the intial PR #365 by focusing on Metropolitan France .

Thank you @jbelien  and @LaoshuBaby  for the help

### CODE REVIEW

**Review by jbelien — CHANGES_REQUESTED** [review]
Hello @l-longour, 

Thanks for this fix.

2 comments:
- Please use `Polygon` instead of `LineString` for the geometry of France
- Please rename `france-metropolitan.geojson` to `france.geojson` ; the file name must match the region id in `config/regions.yaml`

Thanks!

**Comment by llongour** [comment]
Hello, 
I just made the modifications, is it ok ?
Thank you

**Comment by jbelien** [comment]
> I just made the modifications, is it ok ?

Not it's still a `FeatureCollection` instead of just geometry (`Polygon` or `MultiPolygon`) (or `GeometryCollection`).

Here is the area generated via https://polygons.openstreetmap.fr/?id=1403916
```json
{"type":"GeometryCollection","geometries":[{"type":"MultiPolygon","coordinates":[[[[-5.49,48.5],[-5.44,48.59],[-5.38,48.65],[-5.29,48.7],[-4.92,48.79],[-4.65,48.89],[-4.09,49],[-3.76,49.11],[-3.51,49.15],[-3.19,49.15],[-3.17,49.21],[-3.1,49.28],[-2.97,49.34],[-2.71,49.31],[-2.53,49.25],[-2.49,49.1],[-2.49,48.96],[-2.25,48.91],[-2.02,48.92],[-2.02,48.96],[-1.96,49],[-1.89,49.1],[-1.87,49.23],[-1.9,49.27],[-2.02,49.33],[-2.1,49.4],[-2.15,49.46],[-2.18,49.53],[-2.1,49.69],[-2.09,49.94],[-2.07,49.96],[-1.83,49.97],[-1.68,49.93],[-1.57,49.93],[-1.45,49.96],[-1.21,49.95],[-1.08,49.91],[-0.98,49.85],[-0.9,49.74],[-0.88,49.66],[-0.83,49.62],[-0.79,49.62],[-0.73,49.59],[-0.27,49.59],[-0.23,49.66],[-0.23,49.71],[-0.16,49.82],[-0.01,49.91],[0.27,50],[0.44,50.08],[0.74,50.12],[0.86,50.16],[1,50.17],[1.08,50.23],[1.12,50.24],[1.14,50.31],[1.18,50.36],[1.18,50.43],[1.21,50.48],[1.2,50.74],[1.23,50.81],[1.22,50.83],[1.24,50.91],[1.28,50.95],[1.53,51.08],[1.71,51.13],[1.85,51.23],[1.96,51.24],[2.02,51.27],[2.13,51.29],[2.17,51.32],[2.24,51.34],[2.37,51.35],[2.41,51.32],[2.45,51.25],[2.6,51.09],[2.61,51.03],[2.64,51.02],[2.67,50.97],[2.65,50.87],[2.69,50.85],[2.74,50.85],[2.82,50.76],[2.9,50.75],[2.91,50.78],[2.97,50.79],[2.99,50.81],[3.16,50.83],[3.23,50.77],[3.23,50.75],[3.27,50.75],[3.3,50.72],[3.3,50.63],[3.32,50.61],[3.32,50.57],[3.36,50.54],[3.41,50.54],[3.45,50.57],[3.52,50.57],[3.56,50.54],[3.64,50.53],[3.7,50.48],[3.71,50.38],[3.81,50.4],[3.92,50.37],[3.95,50.39],[4.04,50.4],[4.14,50.33],[4.23,50.31],[4.26,50.28],[4.26,50.24],[4.24,50.21],[4.2,50.19],[4.2,50.17],[4.24,50.15],[4.24,50.12],[4.27,50.09],[4.27,50.05],[4.22,50.02],[4.22,50],[4.33,50.01],[4.36,49.99],[4.45,49.98],[4.51,49.99],[4.59,50.03],[4.65,50.03],[4.64,50.09],[4.68,50.13],[4.79,50.2],[4.84,50.21],[4.86,50.19],[4.9,50.19],[4.94,50.15],[4.91,50.07],[4.88,50.05],[4.88,50.02],[4.86,50.01],[4.86,49.99],[4.93,49.93],[4.93,49.89],[4.9,49.86],[4.91,49.83],[5.02,49.84],[5.04,49.81],[5.12,49.8],[5.15,49.76],[5.19,49.74],[5.3,49.73],[5.38,49.66],[5.44,49.64],[5.49,49.59],[5.5,49.55],[5.54,49.57],[5.59,49.56],[5.62,49.59],[5.73,49.58],[5.74,49.6],[5.8,49.6],[5.86,49.58],[5.88,49.54],[5.99,49.53],[6.01,49.49],[6.05,49.51],[6.08,49.5],[6.16,49.55],[6.28,49.55],[6.34,49.51],[6.41,49.52],[6.48,49.51],[6.58,49.46],[6.64,49.38],[6.63,49.34],[6.7,49.31],[6.77,49.21],[6.8,49.21],[6.8,49.23],[6.84,49.26],[6.96,49.26],[7.07,49.22],[7.07,49.19],[7.11,49.2],[7.15,49.17],[7.28,49.16],[7.3,49.18],[7.33,49.18],[7.34,49.21],[7.47,49.22],[7.51,49.21],[7.54,49.18],[7.55,49.13],[7.65,49.11],[7.66,49.09],[7.76,49.09],[7.8,49.11],[7.87,49.08],[7.95,49.1],[8.09,49.03],[8.21,49.01],[8.23,49.02],[8.26,49],[8.27,48.95],[8.16,48.86],[8.14,48.79],[8.09,48.75],[8.06,48.75],[8.03,48.72],[8.01,48.72],[7.97,48.67],[7.85,48.59],[7.84,48.57],[7.85,48.51],[7.81,48.47],[7.77,48.39],[7.79,48.34],[7.78,48.3],[7.76,48.28],[7.73,48.28],[7.7,48.19],[7.67,48.18],[7.61,48.08],[7.61,48.05],[7.66,48],[7.66,47.95],[7.64,47.92],[7.62,47.92],[7.6,47.82],[7.57,47.78],[7.59,47.72],[7.56,47.68],[7.63,47.63],[7.62,47.55],[7.57,47.53],[7.56,47.49],[7.52,47.45],[7.4,47.39],[7.3,47.4],[7.23,47.38],[7.21,47.4],[7.14,47.41],[7.13,47.46],[7.04,47.46],[7.03,47.42],[7.01,47.41],[7.05,47.41],[7.09,47.38],[7.1,47.32],[7.04,47.27],[6.99,47.26],[7,47.24],[6.96,47.19],[6.92,47.18],[6.89,47.13],[6.87,47.13],[6.84,47.1],[6.79,47.09],[6.76,47.06],[6.76,47.03],[6.72,47],[6.68,47],[6.67,46.97],[6.63,46.95],[6.5,46.93],[6.5,46.84],[6.48,46.82],[6.5,46.8],[6.5,46.77],[6.48,46.74],[6.36,46.67],[6.3,46.66],[6.25,46.61],[6.19,46.58],[6.18,46.57],[6.2,46.55],[6.19,46.51],[6.13,46.47],[6.13,46.44],[6.19,46.41],[6.21,46.37],[6.23,46.4],[6.32,46.44],[6.41,46.45],[6.51,46.5],[6.83,46.47],[6.86,46.44],[6.84,46.35],[6.89,46.32],[6.9,46.25],[6.85,46.2],[6.85,46.17],[6.92,46.16],[6.94,46.14],[6.94,46.11],[7.01,46.04],[7.04,46.03],[7.09,45.92],[7.03,45.84],[6.87,45.78],[6.85,45.79],[6.85,45.75],[6.87,45.72],[6.92,45.72],[6.94,45.69],[7.02,45.68],[7.04,45.66],[7.03,45.55],[7.08,45.53],[7.09,45.51],[7.12,45.51],[7.15,45.46],[7.2,45.45],[7.23,45.4],[7.2,45.34],[7.17,45.32],[7.17,45.23],[7.11,45.18],[7.01,45.18],[6.96,45.13],[6.93,45.13],[6.93,45.11],[6.88,45.09],[6.83,45.09],[6.81,45.11],[6.7,45.1],[6.7,45.06],[6.78,45.05],[6.81,44.96],[6.8,44.93],[6.82,44.93],[6.83,44.91],[6.87,44.89],[6.97,44.9],[7.06,44.85],[7.05,44.79],[7.06,44.75],[7.1,44.74],[7.12,44.67],[7.09,44.64],[7,44.65],[7.01,44.6],[6.97,44.58],[6.96,44.54],[6.91,44.52],[6.99,44.44],[6.97,44.39],[6.94,44.39],[7,44.32],[7.03,44.31],[7.04,44.27],[7.1,44.27],[7.21,44.24],[7.22,44.22],[7.28,44.19],[7.35,44.19],[7.38,44.16],[7.52,44.18],[7.56,44.2],[7.6,44.19],[7.62,44.22],[7.69,44.22],[7.72,44.2],[7.72,44.13],[7.76,44.09],[7.75,44.04],[7.68,43.94],[7.6,43.91],[7.6,43.88],[7.55,43.85],[7.58,43.75],[7.65,43.67],[7.67,43.56],[7.56,43.5],[7.53,43.5],[7.51,43.47],[7.49,43.47],[7.48,43.45],[7.46,43.45],[7.45,43.43],[7.43,43.43],[7.42,43.41],[7.4,43.41],[7.39,43.39],[7.37,43.39],[7.36,43.37],[7.27,43.33],[7.24,43.3],[7.01,43.2],[6.99,43.12],[6.95,43.06],[6.85,42.98],[6.76,42.88],[6.61,42.8],[6.46,42.75],[6.15,42.74],[5.83,42.81],[5.76,42.81],[5.59,42.87],[5.49,42.93],[5.33,42.93],[5.06,42.99],[4.93,43.09],[4.78,43.08],[4.71,43.11],[4.52,43.12],[4.29,43.22],[4.17,43.22],[4,43.26],[3.89,43.19],[3.8,43.17],[3.73,43.09],[3.66,43.05],[3.54,43.02],[3.44,43.03],[3.37,42.96],[3.35,42.69],[3.42,42.63],[3.48,42.51],[3.49,42.43],[3.47,42.4],[3.06,42.39],[3.02,42.43],[2.95,42.43],[2.87,42.42],[2.79,42.37],[2.72,42.38],[2.71,42.37],[2.72,42.34],[2.69,42.3],[2.57,42.31],[2.55,42.29],[2.46,42.3],[2.41,42.35],[2.28,42.39],[2.16,42.38],[2.13,42.34],[2.09,42.32],[1.99,42.31],[1.93,42.36],[1.91,42.41],[1.87,42.41],[1.8,42.45],[1.7,42.46],[1.68,42.51],[1.7,42.56],[1.69,42.58],[1.52,42.61],[1.49,42.57],[1.43,42.56],[1.39,42.59],[1.38,42.63],[1.32,42.68],[1.15,42.67],[1.11,42.69],[1.08,42.74],[0.96,42.76],[0.91,42.75],[0.87,42.78],[0.71,42.82],[0.7,42.76],[0.72,42.74],[0.72,42.68],[0.69,42.65],[0.63,42.66],[0.41,42.65],[0.36,42.67],[0.35,42.65],[0.29,42.63],[0.25,42.65],[0.23,42.68],[0.18,42.69],[-0.01,42.64],[-0.09,42.66],[-0.1,42.68],[-0.15,42.7],[-0.15,42.72],[-0.18,42.75],[-0.24,42.76],[-0.3,42.8],[-0.34,42.79],[-0.37,42.76],[-0.5,42.77],[-0.53,42.74],[-0.58,42.74],[-0.66,42.82],[-0.77,42.87],[-0.77,42.93],[-0.8,42.91],[-0.95,42.91],[-1.05,42.96],[-1.16,42.97],[-1.22,43.01],[-1.27,43],[-1.31,43.03],[-1.32,43],[-1.34,42.99],[-1.44,43],[-1.51,43.06],[-1.51,43.11],[-1.45,43.16],[-1.42,43.23],[-1.48,43.23],[-1.53,43.25],[-1.54,43.22],[-1.56,43.21],[-1.62,43.21],[-1.66,43.24],[-1.67,43.27],[-1.76,43.26],[-1.77,43.29],[-1.83,43.34],[-1.81,43.48],[-1.84,43.62],[-1.76,43.7],[-1.75,43.78],[-1.65,44.08],[-1.59,44.36],[-1.58,44.48],[-1.6,44.51],[-1.6,44.62],[-1.54,44.9],[-1.52,45.14],[-1.49,45.29],[-1.49,45.46],[-1.57,45.52],[-1.61,45.59],[-1.62,45.69],[-1.6,45.73],[-1.62,45.77],[-1.7,45.85],[-1.75,46.01],[-1.8,46.04],[-2.06,46.31],[-2.44,46.46],[-2.56,46.49],[-2.64,46.54],[-2.71,46.61],[-2.74,46.67],[-2.71,47],[-2.88,47.07],[-3.03,47.04],[-3.28,47.05],[-3.37,47.07],[-3.47,47.12],[-3.54,47.18],[-3.69,47.41],[-3.9,47.44],[-3.98,47.42],[-4.07,47.42],[-4.19,47.45],[-4.3,47.52],[-4.52,47.56],[-4.56,47.59],[-5.08,47.81],[-5.24,47.86],[-5.32,47.93],[-5.32,47.95],[-5.35,47.98],[-5.36,48.09],[-5.48,48.37],[-5.49,48.47],[-5.49,48.5]]],[[[8.23,42.19],[8.23,42.43],[8.25,42.48],[8.33,42.56],[8.37,42.58],[8.38,42.62],[8.4,42.63],[8.43,42.69],[8.5,42.76],[8.6,42.81],[8.84,42.87],[8.93,42.93],[9.01,42.95],[9.03,42.97],[9.03,43.04],[9.06,43.11],[9.16,43.2],[9.27,43.25],[9.45,43.27],[9.54,43.25],[9.63,43.19],[9.69,42.94],[9.8,42.83],[9.8,42.74],[9.78,42.7],[9.82,42.66],[9.83,42.54],[9.85,42.5],[9.84,42.37],[9.87,42.28],[9.86,42.23],[9.87,42.13],[9.85,42.03],[9.82,41.98],[9.71,41.87],[9.71,41.63],[9.69,41.47],[9.66,41.4],[9.46,41.37],[9.33,41.3],[9.28,41.25],[9.12,41.28],[8.85,41.22],[8.75,41.24],[8.65,41.31],[8.62,41.35],[8.59,41.36],[8.51,41.44],[8.46,41.53],[8.44,41.54],[8.44,41.56],[8.42,41.57],[8.42,41.59],[8.37,41.64],[8.34,41.72],[8.28,41.81],[8.28,41.95],[8.23,42.19]]]]}]}
```

If that geometry is correct, please use it as `france.geojson`.

**Comment by llongour** [comment]
I just modified, it is now with the right format

**Review by jbelien — APPROVED** [review]

**Comment by LaoshuBaby** [comment]
Thank you for value my work in https://github.com/osmbe/osm-welcome-tool/commit/b05eb255f817f13223b2c06eb304edc70927e206 and https://github.com/osmbe/osm-welcome-tool/commit/4fa7982fe99cdf5fdca1b47ac447b00ded79a040, but looks like I've also made geojson mistake that trouble you all. 

By the way I want to know, how can I get a osmcha id with specific geojson? (In https://github.com/osmbe/osm-welcome-tool/blob/2.x/CONTRIBUTING.md#add-a-new-region this was not mentioned, but I want to have a try)

**Pull request merged**
