### PR TITLE
Add Bulgaria

### PR DESCRIPTION
**Pull request by Dimitar5555**

### CODE REVIEW

**Comment by jbelien** [comment]
Awesome, thanks @Dimitar5555 !

I'll take care of this right now.

**Review by jbelien — CHANGES_REQUESTED** [review]
I added Bulgarian translation files.
Could you update [`messages+intl-icu.bg.xlf`](https://github.com/osmbe/osm-welcome-tool/blob/c3e08e9ff5b588b15e67173429012d307ba3b46d/translations/messages+intl-icu.bg.xlf) with the correct translations in Bulgarian (by translating the `<target>` elements from English to Bulgarian) ? Thanks.

**Comment by Dimitar5555** [comment]
@jbelien It's translated now.

**Review by jbelien — APPROVED** [review]

**Comment by jbelien** [comment]
Awesome work, thanks @Dimitar5555 👍 

Bulgaria (and Bulgarian language) are now added to https://welcome.osm.be/ 🚀

**Pull request merged**
