### PR TITLE
Added Polish welcome message template

### PR DESCRIPTION
**Pull request by RicoElectrico**

### CODE REVIEW

**Comment by matkoniecz** [comment]
As someone from Poland: looks well, though a bit overloaded with links.

**Comment by RicoElectrico** [comment]
> 
> 
> As someone from Poland: looks well, though a bit overloaded with links.

It is somewhat based on my personal experience: I met a person who edited for a long time not knowing that many of the listed items exist at all. I assume that one-time or careless mappers will ignore it anyway, and it will be a value added for diligent mappers.

We may fine-tune the message in the future; for now let's have something and gauge the reaction (greeters can mark that user replied and/or leave internal notes about them).

The message is also only a template, the welcoming user can edit it before sending as well.

**Comment by RicoElectrico** [comment]
@jbelien When can we expect the deployment? I'd like to make an introduction for the Polish community :)

**Comment by jbelien** [comment]
> @jbelien When can we expect the deployment? I'd like to make an introduction for the Polish community :)

I'll take care of it this weekend.
I'll ping you when it's deployed.

**Comment by jbelien** [comment]
🚀 Deployed!

**Pull request merged**
