### PR TITLE
Add California

### PR DESCRIPTION
**Pull request by arch0345**

### CODE REVIEW

**Review by jbelien — CHANGES_REQUESTED** [review]
Hello @arch0345 ,

Thanks for your contribution!

I get the following 2 warnings with your GeoJSON:
-  GeometryCollection with a single geometry should be avoided in favor of single part or a single object of multi-part type
- Polygons and MultiPolygons should follow the right-hand rule

Could you make sure to upload a valid GeoJSON?  
You can check this here: https://geojsonlint.com/

Thanks!

**Comment by arch0345** [comment]
Thanks for letting me know about this.

I noticed that the majority of geojsons in this repository get at least one of these warnings on https://geojsonlint.com/. Should I open another PR to fix these?

**Comment by jbelien** [comment]
> I noticed that the majority of geojsons in this repository get at least one of these warnings on https://geojsonlint.com/. Should I open another PR to fix these?

Oh yes, that would be absolutely awesome! 👍
I must admit I didn't check it all while adding a new region ; I should add it as a check in the GitHub Actions workflow.

**Review by jbelien — APPROVED** [review]

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/north-america/california/list

Data will be automatically updated with the next run in a few hours.

**Pull request merged**
