### PR TITLE
Rewind/simplify geojsons

### PR DESCRIPTION
**Pull request by arch0345**
* Rewinds geojsons to follow the right-hand rule
* Simplifies coordinates to the 5th decimal place
* Replaces GeometryCollections with a single geometry with a single Polygon/MultiPolygon

Re: #836

### CODE REVIEW

**Comment by jbelien** [comment]
Really awesome!
I'll review it later today.
And I'll add [`@mapbox/geojsonhint`](https://www.npmjs.com/package/@mapbox/geojsonhint) to the GitHub Actions workflow so all future GeoJSON are properly checked!

I would have kept 6 decimals (because it's what's [recommended by the standard](https://www.rfc-editor.org/rfc/rfc7946#section-11.2)) but in our use case it makes really no difference. 😄

**Comment by jbelien** [comment]
Just being curious, what tool did you use to validate all those GeoJSON files ?

**Comment by arch0345** [comment]
> Just being curious, what tool did you use to validate all those GeoJSON files ?

I used a [modified script](https://github.com/arch0345/osm-welcome-tool/blob/build-regions/scripts/build_regions.js) based on [this one](https://github.com/osmlab/name-suggestion-index/blob/main/scripts/build_features.js) in [`name-suggestion-index`](https://github.com/osmlab/name-suggestion-index) to rewind GeoJSONs that weren't following the right-hand rule using [`@mapbox/geojson-rewind`](https://npmjs.com/package/@mapbox/geojson-rewind), simplify coordinates using [`geojson-precision`](https://npmjs.com/package/geojson-precision), and warn about GeometryCollections. I copy pasted some of the modified files on https://geojsonlint.com/ to make sure this worked.

**Comment by jbelien** [comment]
Awesome improvement! Thanks a lot @arch0345 👍

**Pull request merged**
