### PR TITLE
Add zh-CN Translation

### PR DESCRIPTION
**Pull request by LaoshuBaby**
Hello, maintainers of osm-welcome-tool

This is a translation for 3 xlf files in Simplified Chinese

Wish this can be shown in osmwt, If there are any wrong in those files, please point it to me! Thanks!

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
For just added Catalan region, maybe this can help

```xlf
      <trans-unit id="OMKd.Cf" resname="Catalan Countries">
        <source>Catalan Countries</source>
        <target>加泰罗尼亚</target>
      </trans-unit>
```

https://github.com/OSMChina/osm-welcome-tool/commit/1f730f7ab8036746d77ca4d2a587b503a10eee3c

**Comment by jbelien** [comment]
> For just added Catalan region, maybe this can help

Awesome! You made the change faster than I wrote the request to change it! 😄

**Comment by LaoshuBaby** [comment]
```xml
<trans-unit id="EENoKQM" resname="China">
  <source>China</source>
  <target>中国</target>
</trans-unit>
```

**Review by jbelien — CHANGES_REQUESTED** [review]
The translation for China in Chinese (`zh_CN`) is missing (following eddc611ca41122dc2e955d531cc099d361ddbf04).
```xml
<trans-unit id="EENoKQM" resname="China">
  <source>China</source>
  <target>China</target>
</trans-unit>
```

**Review by jbelien — APPROVED** [review]

**Comment by LaoshuBaby** [comment]
<s>What should I do next?

If for other language's translation, you can refer to https://www.openstreetmap.org/relation/270056

I copyed those from this relation's page

```
name:bg | Китай
name:de | China
name:en | China
name:es | China
name:fr | Chine
name:it | Cina
name:ja | 中国
name:nl | China
name:pl | Chiny
name:sq | Kina
name:zh-Hant | 中國
```

(the `zh-Hant` can be seen as `zh-TW` in most case)</s>

Oh! I see, this was added in #258 ! Thank you! ♥

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/?l=zh_CN

**Pull request merged**
