### PR TITLE
Adding support for country of Serbia

### PR DESCRIPTION
**Pull request by stalker314314**
As per discussion at https://community.openstreetmap.org/t/dodavanje-na-welcome-osm-be/114304 we are requesting adding of Serbia here. OsmCha.id is left empty.

Only "non-conventional" thing is addition of two scripts of same language - Serbian Cyrillic and Serbian Latin. I didn't see any other language here using templates with different script, so I was not quite sure about directory name - does it relate to ISO 639 or is it just for display. In KDE/Gnome/Linux world, it is usually `sr@latin` or `sr-latin`, but I kept it here in the spirit of OSM name tag `name:sr-Latn`. Let me know what is preferred, so I can change it accordingly.

### CODE REVIEW

**Comment by stalker314314** [comment]
Hi, @jbelien , friendly ping to take a look when you find time!:)

**Comment by jbelien** [comment]
> Only "non-conventional" thing is addition of two scripts of same language - Serbian Cyrillic and Serbian Latin. I didn't see any other language here using templates with different script, so I was not quite sure about directory name - does it relate to ISO 639 or is it just for display. In KDE/Gnome/Linux world, it is usually sr@latin or sr-latin, but I kept it here in the spirit of OSM name tag name:sr-Latn. Let me know what is preferred, so I can change it accordingly.

Symfony is based on https://icu.unicode.org/ and I think the correct code will be `sr_Latn`. I've made the necessary change.

**Review by jbelien — APPROVED** [review]

**Comment by stalker314314** [comment]
Thanks! BTW, glad to see welcome.osm.be is alive and kickin'!:)

**Comment by stalker314314** [comment]
@jbelien I noticed small bug, not sure where it lies. When I am on welcome message page, I cannot see latin message:
slika

If I click second language, I have URL with `locale=sr_Latn&template=default.md` loaded, but I still see cyrillic version of template. Like https://github.com/osmbe/osm-welcome-tool/blob/2.x/templates/messages/serbia/sr_Latn/default.md is not loading? I don't see anything in console, but I don't think this is frontend problem.

Side question: both labels are saying "Default (Serbian)", any way to change that to "Default (Serbian cyr)" and "Default (Serbian lat)" or something similar?

**Comment by jbelien** [comment]
I've opened an new issue ( #1464 ), I'll investigate 👍

**Pull request merged**
